# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'GitHubUsersListApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for GitHubUsersListApp
    pod 'RxSwift',         '6.5.0'
    pod 'SwiftyJSON',      '~> 5.0.0'
    pod 'Alamofire',       '~> 5.5'
    pod 'Then'                          
    pod 'SnapKit'
    pod 'MJRefresh'
    pod 'Kingfisher'
    pod 'Toast'

  target 'GitHubUsersListAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitHubUsersListAppUITests' do
    # Pods for testing
  end

end
