# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'QRApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QRApp
  pod 'Alamofire', '~> 3.4'
  pod "QRCode", "~> 0.5"
  pod 'PKHUD'
  target 'QRAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
