source 'https://git.oschina.net/6david9/Specs.git'
platform :ios, '8.0'

target 'QR' do
    use_frameworks!
    pod 'QRCodeReader.swift', '~> 5.2.0'
    pod 'Alamofire', '~> 3.0.0'
    pod "PKHUD", '~>3.1.0'
end
