# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'GithubUser' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
  pod 'MJRefresh', '~> 3.7.5'
  pod 'Alamofire', '~> 5.5'
  pod 'HandyJSON', '~> 5.0.2' 
  pod 'SnapKit',   '~> 5.0.1'
  pod 'Kingfisher'#, '~> 7.0'
  # Pods for GithubUser

end
