platform :ios, '13.0'

inhibit_all_warnings!

target 'MobileTest' do

  use_frameworks!


  pod 'Alamofire', '~> 5.2'
  pod 'RxSwift', '6.0.0'
  pod 'RxCocoa', '6.0.0'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'MJRefresh'
end

