use_frameworks!

platform :ios, '8.0'

target 'QRGenerator' do
    pod 'SnapKit', '~> 4.0.0'
    pod 'ObjectMapper', '~> 3.1'
    pod 'Moya', '~> 10.0.0'
    pod 'Toast-Swift', '~> 3.0.1'
    pod 'RHSideButtons'
end



target 'QRGeneratorTests' do
    pod 'SnapKit', '~> 4.0.0'
    pod 'ObjectMapper', '~> 3.1'
    pod 'Moya', '~> 10.0.0'
    pod 'Toast-Swift', '~> 3.0.1'
end
