# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'GitUserApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitUserApp

  target 'GitUserAppTests' do
    inherit! :search_paths
    pod 'Alamofire'
    pod 'Kingfisher'
    pod 'SnapKit'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Moya'
    pod 'Moya/RxSwift'
    pod 'ObjectMapper'
    pod 'Moya-ObjectMapper'
    pod 'Moya-ObjectMapper/RxSwift'
    pod 'Result'
    pod 'MJRefresh'
  end

end
