inhibit_all_warnings!
platform:'ios', '14.0'

target 'test_mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test_mobile
  pod 'Moya/RxSwift'
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'RxOptional'
  pod 'NSObject+Rx'
  pod 'Reusable'
  pod 'RxDataSources'
  pod 'Resolver'
  pod 'Nuke', :git => 'https://github.com/kean/Nuke', :branch => 'master'

  target 'test_mobileTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking'
  end

  target 'test_mobileUITests' do
    # Pods for testing
  end

end
